project 'Todoey.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Todoey' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework', '~> 2.1'

  # Pods for Todoey

end
