project 'IBMSeefood.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IBMSeefood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SVProgressHUD'
    pod 'IBMWatsonVisualRecognitionV3', '~> 2.1.1'

  # Pods for IBMSeefood

end
